name = "ayp-trackid"
main = "src/worker.js"
compatibility_date = "2025-06-01"

[ai]
binding = "AI"
remote = true

routes = [
  { pattern = "trackid.alwaysyesterday.party", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
